// client/pages/metadata.vue
<template>
  <div class="container">
    <h1>メタデータを作成する</h1>
    <p>あなたのアカウントにメタデータを作成します。手数料はかかりません。</p>

    <b-form>
      <b-form-group label="Private Key" label-for="inputPrivateKey">
        <b-form-input
          id="inputPrivateKey"
          v-model="privateKey"
          type="text"
          name="privateKey"
          placeholder="Test Private Key"
        />
        <div class="text-right">
          Address: {{ address }}
        </div>
      </b-form-group>
      <b-form-group label="Metadata Key" label-for="inputMetadataKey">
        <b-form-input
          id="inputMetadataKey"
          v-model="metadataKey"
          type="text"
          name="metadataKey"
          placeholder="Metadata Key"
        />
        <div class="text-right">
          Generated Key: {{ metadataKeyId }}
        </div>
      </b-form-group>
      <b-form-group label="Metadata Value" label-for="inputMetadataValue">
        <b-form-input
          id="inputMetadataValue"
          v-model="metadataValue"
          type="text"
          name="metadataValue"
          placeholder="Metadata Value"
        />
        <div class="text-right">
          Hex Value: {{ metadataValueHex }}
        </div>
      </b-form-group>
      <b-form-group>
        <template v-if="sending">
          <b-button disabled variant="primary">
            メタデータを取得する
          </b-button>
        </template>
        <template v-else>
          <b-button variant="primary" @click="handleGet">
            メタデータを取得する
          </b-button>
        </template>
      </b-form-group>
      <b-form-group>
        <template v-if="sending">
          <b-button disabled variant="danger">
            メタデータを設定する
          </b-button>
        </template>
        <template v-else>
          <b-button variant="danger" @click="handleSend">
            メタデータを設定する
          </b-button>
        </template>
      </b-form-group>
    </b-form>

    <section class="mb-3">
      <h4>メタデータ</h4>
      <template v-if="metadata.length === 0">
        <p>未取得もしくは未設定</p>
      </template>
      <template v-else>
        <b-table responsive="true" size="sm">
          <thead>
            <tr>
              <th>Key</th>
              <th>Value</th>
              <th>Sender Public Key</th>
              <th>Target Public Key</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="m in metadata" :key="m.key">
              <th scope="row">
                {{ m.key }}}
              </th>
              <td>{{ m.value }}}</td>
              <td class="public-key-ellipsis">
                {{ m.senderPublicKey }}}
              </td>
              <td class="public-key-ellipsis">
                {{ m.targetPublicKey }}}
              </td>
            </tr>
          </tbody>
        </b-table>
      </template>
    </section>

    <section class="mb-3">
      <h4>送信済みトランザクション</h4>
      <ul>
        <li v-for="hash in hashes" :key="hash">
          <a
            :href="transactionStatus(hash)"
            target="_blank"
          >{{ hash }}}</a>
        </li>
        <li v-if="hashes.length === 0">
          なし
        </li>
      </ul>
    </section>
  </div>
</template>

<script>
import { Account, Convert, KeyGenerator, NetworkType } from 'symbol-sdk'

export default {
  components: {
  },
  data () {
    return {
      metadata: [],
      hashes: [],
      announces: [],
      privateKey: '',
      metadataKey: '',
      metadataValue: '',
      sending: false,
      getting: false
    }
  },
  computed: {
    address () {
      try {
        const account = Account.createFromPrivateKey(this.privateKey, NetworkType.TEST_NET)
        return account.address.pretty()
      } catch (e) {
        return ''
      }
    },
    metadataKeyId () {
      try {
        return KeyGenerator.generateUInt64Key(this.metadataKey).toHex()
      } catch (e) {
        return ''
      }
    },
    metadataValueHex () {
      return Convert.utf8ToHex(this.metadataValue)
    }
  },
  methods: {
    handleGet () {
      this.metadata = []
      try {
        this.getting = this.$get(this.privateKey)
          .then((data) => {
            this.metadata = data
          })
      } catch (e) {
        this.$bvToast.toast(e.message, {
          title: 'Error',
          autoHideDelay: 5000,
          appendToast: true
        })
      }
    },
    handleSend () {
      try {
        this.sending = this.$send(this.privateKey, this.metadataKey, this.metadataValue)
          .then(({ transactionHash, announceResponse }) => {
            this.hashes = [...this.hashes, transactionHash]
            this.announces = [...this.announces, announceResponse]
          })
      } catch (e) {
        this.$bvToast.toast(e.message, {
          title: 'Error',
          autoHideDelay: 5000,
          appendToast: true
        })
      }
    },
    transactionStatus (hash) {
      return `${process.env.NODE_URL}/transactionStatus/${hash}`
    }
  }
}
</script>

<style scoped>
.public-key-ellipsis {
  font-family: Consolas, monospace;
  overflow: hidden;
  max-width: 5rem;
  white-space: nowrap;
  text-overflow: ellipsis;
}
</style>

// client/src/routes/metadata.svelte
<script>
    import { Button, Form, FormGroup, Input, Label, Table, Toast, ToastBody, ToastHeader } from 'sveltestrap';
    import send from '../lib/send';
    import get from '../lib/get';
    import { privateKey } from '../stores.js';
    import { Account, Convert, KeyGenerator, NetworkType } from 'nem2-sdk';

    export const name = 'metadata';

    let toasts = [];

    let metadataKey = "";
    let metadataValue = "";

    let sending = Promise.resolve();
    let getting = Promise.resolve();

    let hashes = [], announces = [], metadata = [];

    let address = '', metadataKeyId = '', metadataValueHex = '';

    $: {
        try {
            const account = Account.createFromPrivateKey($privateKey, NetworkType.TEST_NET);
            address = account.address.pretty();
        } catch (e) {
            address = "";
        }
    }

    $: {
        try {
            metadataKeyId = KeyGenerator.generateUInt64Key(metadataKey).toHex()
        } catch (e) {
            metadataKeyId = ''
        }
    }

    $: metadataValueHex = Convert.utf8ToHex(metadataValue);

    function handleSend(event) {
        event.preventDefault();
        try {
            sending = send($privateKey, metadataKey, metadataValue)
                .then(({transactionHash, announceResponse}) => {
                    hashes = [...hashes, transactionHash];
                    announces = [...announces, announceResponse];
                })
        } catch(e) {
            toasts = [{
                isOpen: true,
                header: 'Error',
                body: e.message
            }, ...toasts]
        }
    }

    function handleGet(event) {
        event.preventDefault();
        metadata = [];
        try {
            getting = get($privateKey)
                .then((data) => {
                    metadata = data;
                })
        } catch(e) {
            toasts = [{
                isOpen: true,
                header: 'Error',
                body: e.message
            }, ...toasts]
        }
    }
</script>

<style>
    .public-key-ellipsis {
        font-family: Consolas, monospace;
        overflow: hidden;
        max-width: 5rem;
        white-space: nowrap;
        text-overflow: ellipsis;
    }
</style>

<svelte:head>
    <title>Metadata</title>
</svelte:head>

<div class="position-fixed" style="right: 1rem; top: 1rem;">
    {#each toasts as toast}
        <Toast isOpen={toast.isOpen}>
            <ToastHeader toggle="{() => toast.isOpen = !toast.isOpen}" icon={"danger"}>
                {toast.header}
            </ToastHeader>
            <ToastBody>
                {toast.body}
            </ToastBody>
        </Toast>
    {/each}
</div>

<h1>メタデータを作成する</h1>
<p>あなたのアカウントにメタデータを作成します。手数料はかかりません。</p>

<Form>
    <FormGroup>
        <Label for="inputPrivateKey">Private Key</Label>
        <Input
                type="text"
                name="privateKey"
                id="inputPrivateKey"
                bind:value={$privateKey}
                placeholder="Test Private Key" />
        <div class="text-right">Address: {address}</div>
    </FormGroup>
    <FormGroup>
        <Label for="inputMetadataKey">Metadata Key</Label>
        <Input
                type="text"
                name="metadataKey"
                id="inputMetadataKey"
                bind:value={metadataKey}
                placeholder="Metadata Key" />
        <div class="text-right">Generated Key: {metadataKeyId}</div>
    </FormGroup>
    <FormGroup>
        <Label for="inputMetadataValue">Metadata Value</Label>
        <Input
                type="text"
                name="metadataValue"
                id="inputMetadataValue"
                bind:value={metadataValue}
                placeholder="Metadata Value" />
        <div class="text-right">Hex Value: {metadataValueHex}</div>
    </FormGroup>
    <FormGroup>
        {#await sending}
            <Button disabled color="primary">メタデータを取得する</Button>
        {:then _}
            <Button on:click={handleGet} color="primary">メタデータを取得する</Button>
        {/await}
    </FormGroup>
    <FormGroup>
        {#await sending}
            <Button disabled color="danger">メタデータを設定する</Button>
        {:then _}
            <Button on:click={handleSend} color="danger">メタデータを設定する</Button>
        {/await}
    </FormGroup>
</Form>

<section class="mb-3">
    <h4>メタデータ</h4>
    {#if metadata.length === 0}
        <p>未取得もしくは未設定</p>
    {:else}
        <Table responsive size="sm">
            <thead>
            <tr>
                <th>Key</th>
                <th>Value</th>
                <th>Sender Public Key</th>
                <th>Target Public Key</th>
            </tr>
            </thead>
            <tbody>
            {#each metadata as m}
                <tr>
                    <th scope="row">{m.key}</th>
                    <td>{m.value}</td>
                    <td class="public-key-ellipsis">{m.senderPublicKey}</td>
                    <td class="public-key-ellipsis">{m.targetPublicKey}</td>
                </tr>
            {/each}
            </tbody>
        </Table>
    {/if}
</section>

<section class="mb-3">
    <h4>送信済みトランザクション</h4>
    <ul>
    {#each hashes as hash}
        <li>
            <a href={`https://test-api.48gh23s.xyz:3001/transaction/${hash}/status`} target="_blank">{hash}</a>
        </li>
    {/each}
    {#if hashes.length === 0}
        <li>なし</li>
    {/if}
    </ul>
</section>
